/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.L_UPSDatos;
import com.sun.awt.AWTUtilities;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kandskat
 */
public class FrmGestion_UPS_Datos extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestion_UPS_Datos
     */
    public FrmGestion_UPS_Datos() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_UPS_Datos_ConvToExel = new javax.swing.JLabel();
        Lbl_UPS_Datos_Agregar = new javax.swing.JLabel();
        Lbl_UPS_Datos_Mail = new javax.swing.JLabel();
        Lbl_UPS_Datos_Actualizar = new javax.swing.JLabel();
        Lbl_UPS_Datos_Buscar = new javax.swing.JLabel();
        Txt_UPS_Datos_Buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_UPS_Datos_Mostrando = new javax.swing.JTable();
        Lbl_UPS_Datos_Panel_01 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 10, 20));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 10, 20));

        Lbl_UPS_Datos_ConvToExel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Lbl_UPS_Datos_ConvToExel, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 50, 50));

        Lbl_UPS_Datos_Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Lbl_UPS_Datos_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 50, 50));

        Lbl_UPS_Datos_Mail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Lbl_UPS_Datos_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 50, 50));

        Lbl_UPS_Datos_Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Lbl_UPS_Datos_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 60, 50));

        Lbl_UPS_Datos_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_UPS_Datos_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_UPS_Datos_BuscarMouseClicked(evt);
            }
        });
        getContentPane().add(Lbl_UPS_Datos_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 120, 30));

        Txt_UPS_Datos_Buscar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Txt_UPS_Datos_Buscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 290, 20));

        Tbl_UPS_Datos_Mostrando.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        Tbl_UPS_Datos_Mostrando.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_UPS_Datos_Mostrando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_UPS_Datos_MostrandoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_UPS_Datos_Mostrando);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 960, 220));

        Lbl_UPS_Datos_Panel_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/File/FramePrincipalUD.png"))); // NOI18N
        getContentPane().add(Lbl_UPS_Datos_Panel_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Lbl_UPS_Datos_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_UPS_Datos_BuscarMouseClicked
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        try {
            DefaultTableModel model;
            L_UPSDatos func = new L_UPSDatos();
            model=func.MostrandoDatos(Txt_UPS_Datos_Buscar.getText());
            
            Tbl_UPS_Datos_Mostrando.setModel(model);
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_Lbl_UPS_Datos_BuscarMouseClicked

    public static String UbicarPuntoUPS="";
    private void Tbl_UPS_Datos_MostrandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_UPS_Datos_MostrandoMouseClicked
        // TODO add your handling code here:
        
        //Recordar completar el codigo con el valor dentro de la fila a la cual se ace referencia
        //la columna es 0 es decir no varia puesto que usaremos siempre la primera columna como referencia
        
        String buscar;
        int fila = Tbl_UPS_Datos_Mostrando.rowAtPoint(evt.getPoint());
        buscar = Tbl_UPS_Datos_Mostrando.getValueAt(fila, 0).toString();
        UbicarPuntoUPS=buscar;
        FrmGestion_UPS_Datos_Detalle frm_ups_detalle = new FrmGestion_UPS_Datos_Detalle();
        frm_ups_detalle.setVisible(true);
        frm_ups_detalle.toFront();
    }//GEN-LAST:event_Tbl_UPS_Datos_MostrandoMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        setExtendedState(FrmGestion_UPS_Datos.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestion_UPS_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_UPS_Datos_Actualizar;
    private javax.swing.JLabel Lbl_UPS_Datos_Agregar;
    private javax.swing.JLabel Lbl_UPS_Datos_Buscar;
    private javax.swing.JLabel Lbl_UPS_Datos_ConvToExel;
    private javax.swing.JLabel Lbl_UPS_Datos_Mail;
    private javax.swing.JLabel Lbl_UPS_Datos_Panel_01;
    private javax.swing.JTable Tbl_UPS_Datos_Mostrando;
    private javax.swing.JTextField Txt_UPS_Datos_Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
