/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author kandskat
 */
public class FrmGestion_UPS_Datos_Detalle extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Gestion_UPS_Datos_Detalle
     */
    public FrmGestion_UPS_Datos_Detalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_UPS_Datos_Detalle_Buscar = new javax.swing.JTextField();
        Txt_UPS_Datos_Detalle_Direccion = new javax.swing.JTextField();
        Txt_UPS_Datos_Detalle_NroATM = new javax.swing.JTextField();
        Txt_UPS_Datos_Detalle_IP = new javax.swing.JTextField();
        Txt_UPS_Datos_Detalle_MskSr = new javax.swing.JTextField();
        Txt_UPS_Datos_Detalle_Capacidad = new javax.swing.JTextField();
        Txt_UPS_Datos_Detalle_MarcaModel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_UPS_Datos_Detalle_Buscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Detalle_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 300, -1));

        Txt_UPS_Datos_Detalle_Direccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Detalle_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, -1));

        Txt_UPS_Datos_Detalle_NroATM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Detalle_NroATM, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 120, -1));

        Txt_UPS_Datos_Detalle_IP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Detalle_IP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 120, -1));

        Txt_UPS_Datos_Detalle_MskSr.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Detalle_MskSr, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 120, -1));

        Txt_UPS_Datos_Detalle_Capacidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Detalle_Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 110, -1));

        Txt_UPS_Datos_Detalle_MarcaModel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Txt_UPS_Datos_Detalle_MarcaModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/File/FrmUpsDatos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestion_UPS_Datos_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestion_UPS_Datos_Detalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_UPS_Datos_Detalle_Buscar;
    private javax.swing.JTextField Txt_UPS_Datos_Detalle_Capacidad;
    private javax.swing.JTextField Txt_UPS_Datos_Detalle_Direccion;
    private javax.swing.JTextField Txt_UPS_Datos_Detalle_IP;
    private javax.swing.JTextField Txt_UPS_Datos_Detalle_MarcaModel;
    private javax.swing.JTextField Txt_UPS_Datos_Detalle_MskSr;
    private javax.swing.JTextField Txt_UPS_Datos_Detalle_NroATM;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
